export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",

  INCIDENT_NOT_FOUND: "INCIDENT_NOT_FOUND",
  INCIDENT_ALREADY_RESOLVED: "INCIDENT_ALREADY_RESOLVED",
  INCIDENT_ACCESS_DENIED: "INCIDENT_ACCESS_DENIED",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
};
